### ISSUE TITLE
Plans for Tauri v2

### ISSUE THREAD

**Issue by lucanisi** [bagindo/tauri-plugin-keygen#2]
Hi,

I noticed in the README that development of the plugin for version 2 stable of Tauri is planned. However, I wanted to ask if there are any specific timelines or plans for when this will be released.

In the meantime, is there any recommended workaround or method to utilize the functionalities of the plugin version 1 with Tauri version 2? Any guidance would be greatly appreciated.

Thank you for your work!

**Comment by bagindo** [comment]
Hi Luca, I'm planning to add the v2 by the end of this month.
Hopefully sooner!

**Comment by lucanisi** [comment]
> Hi Luca, I'm planning to add the v2 by the end of this month. Hopefully sooner!

Great! I'll be looking forward to it, thanks again for your work 😃

**Comment by lucanisi** [comment]
Hi @bagindo! Is there any progress about this?
Thank you!

**Comment by bagindo** [comment]
Hi @lucanisi been busy. It's in the back of my mind every day. will aim for next weekend!

**Comment by lucanisi** [comment]
Absolutely, didn't mean to rush you at all! Thank you again for the support and patience

**Comment by backware-nordalf** [comment]
@bagindo - were you able to support this during your weekend?

**Comment by Nordalf** [comment]
Hey @bagindo ,

I have created a PR which upgrades the library to v2. Was a nightmare but it works now (including the examples).

I suggest we create a new branch named v2 to support backward compatibility

**Comment by Nordalf** [comment]
@lucanisi - if you want to test this out, you can insert below in your `Cargo.toml`. Atleast until a `v2` branch is created in this repo 👍. You can still follow the same documentation

`tauri-plugin-keygen = { git = "https://github.com/Nordalf/tauri-plugin-keygen", branch = "feat/upgrade-tauri-version-2" }`

**Comment by lucanisi** [comment]
> @lucanisi - if you want to test this out, you can insert below in your `Cargo.toml`. Atleast until a `v2` branch is created in this repo 👍. You can still follow the same documentation
> 
> `tauri-plugin-keygen = { git = "https://github.com/Nordalf/tauri-plugin-keygen", branch = "feat/upgrade-tauri-version-2" }`

I just had the chance to test it and it works like a charm! I just had to use your guest-js/index.ts to invoke the v2 version of tauri invoke correctly! I am using it right now and everything seems to work great (self hosted version of keygen.sh). 

Thank you so much for your work! I look forward to switch to the v2 branch of this repo, but I will keep using yours now 😃

**Comment by bagindo** [comment]
@Nordalf thanks for the contribution! Will finally have time this weekend, review things, and merge it.

**Comment by Nordalf** [comment]
> @Nordalf thanks for the contribution! Will finally have time this weekend, review things, and merge it.

@bagindo - happy to help out. This is a great plugin.

**Comment by bagindo** [comment]
merged!
