### ISSUE TITLE
Is there a way to get the license key from rust side?

### ISSUE THREAD

**Issue by lucabrini** [bagindo/tauri-plugin-keygen#3]
Hello @bagindo, I would like to get the license from rust side 'cause I need to use the key in order to ask for updates but I noticed that the tauri_keygen_plugin rust functions are not "exported" to the external of the package.

Am I missing something or does it needs any actual change to the codebase?

**Comment by bagindo** [comment]
Hi Luca, you don't miss anything. I intentionally made the plugin api to only be exposable through the tauri commands (accessible from JavaScript). But I can expose it to the rust side too this weekend. What else do you need other than the license key?

As for auto update, I thought about implementing it here on this plugin. But on Tauri v2 launch, they made a plugin for that, so I thought why re-inventing the wheel.

If you're using the official updater plugin from Tauri, which is accessible from JavaScript bindings, you can pass the license key from the JavaScript to implement auto updates.

This is why I didn't think I need to expose the plugin Keygen api on the rust side. But I'll do it anyway this weekend 👌🏾

**Comment by lucabrini** [comment]
Hello,

No worries, I’ve found a workaround for my use case! I’m now passing the license key from Javascript to the Rust side using events.

I attempted to make these changes myself, I wanted to make the `LicensedState` public so I could access it from the app handle. However, this led to other errors that were a bit too complex for me as a Rust newbie to troubleshoot.

Thank you for your effort! I appreciate it!
